### ISSUE TITLE
Gallerymanager destructor missing quitting of worker thread

### ISSUE THREAD

**Issue by ThomasVogelpohl** [jchaos/QML-ImagePicker#1]
Hi,

I have just tried you nice example and found that I got an error msg on macOS.

The issue is that the gallerymanager does not destroy the created worker thread.
This could be solved like this:
```
GalleryManager::~GalleryManager() 
{

    galleryWorkerThread.quit();
    galleryWorkerThread.wait();
}
```

Best regards,
Thomas

**Comment by jchaos** [comment]
Hi Thomas, 
I have pasted your code into this project.

Best regards.
